version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Windows / Linux Electron dependencies
  - package-ecosystem: "npm"
    directory: "/windows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Web player dependencies
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
