[package]
name = "kumone-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
aes = "0.8"
base64 = "0.22"
cbc = { version = "0.1", features = ["alloc"] }
cipher = { version = "0.4", features = ["alloc", "block-padding"] }
ecb = { version = "0.1", features = ["alloc"] }
hex = "0.4"
md-5 = "0.10"
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[lints]
workspace = true
