[package]
name = "kumone-windows"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
name = "kumone_windows_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
kumone-core = { path = "../../../crates/kumone-core" }
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
